"""
Public company ticker database for autocomplete.
Includes major S&P 500 companies + notable large-caps.
Used for type-ahead suggestions in the search box.
"""

# Format: (ticker, company_name, industry)
TICKERS = [
    ("AAPL", "Apple Inc.", "Technology"),
    ("MSFT", "Microsoft Corporation", "Technology"),
    ("GOOGL", "Alphabet Inc.", "Technology"),
    ("AMZN", "Amazon.com Inc.", "E-Commerce / Cloud"),
    ("NVDA", "NVIDIA Corporation", "Semiconductors"),
    ("META", "Meta Platforms Inc.", "Technology"),
    ("TSLA", "Tesla Inc.", "Automotive / Energy"),
    ("BRK.B", "Berkshire Hathaway", "Conglomerate"),
    ("JPM", "JPMorgan Chase & Co.", "Financial Services"),
    ("JNJ", "Johnson & Johnson", "Healthcare"),
    ("V", "Visa Inc.", "Financial Services"),
    ("UNH", "UnitedHealth Group", "Healthcare"),
    ("PG", "Procter & Gamble Co.", "Consumer Goods"),
    ("HD", "The Home Depot Inc.", "Retail"),
    ("MA", "Mastercard Inc.", "Financial Services"),
    ("DIS", "The Walt Disney Company", "Entertainment"),
    ("BAC", "Bank of America Corp.", "Financial Services"),
    ("XOM", "Exxon Mobil Corporation", "Energy"),
    ("CVX", "Chevron Corporation", "Energy"),
    ("PFE", "Pfizer Inc.", "Pharmaceuticals"),
    ("ABBV", "AbbVie Inc.", "Pharmaceuticals"),
    ("KO", "The Coca-Cola Company", "Beverages"),
    ("PEP", "PepsiCo Inc.", "Beverages / Snacks"),
    ("COST", "Costco Wholesale Corp.", "Retail"),
    ("MRK", "Merck & Co. Inc.", "Pharmaceuticals"),
    ("WMT", "Walmart Inc.", "Retail"),
    ("TMO", "Thermo Fisher Scientific", "Life Sciences"),
    ("CSCO", "Cisco Systems Inc.", "Networking"),
    ("ABT", "Abbott Laboratories", "Healthcare"),
    ("CRM", "Salesforce Inc.", "Cloud Software"),
    ("ACN", "Accenture plc", "Consulting / IT"),
    ("NKE", "Nike Inc.", "Apparel / Retail"),
    ("LIN", "Linde plc", "Industrial Gases"),
    ("ORCL", "Oracle Corporation", "Enterprise Software"),
    ("TXN", "Texas Instruments", "Semiconductors"),
    ("AMD", "Advanced Micro Devices", "Semiconductors"),
    ("INTC", "Intel Corporation", "Semiconductors"),
    ("NEE", "NextEra Energy Inc.", "Utilities / Renewables"),
    ("UPS", "United Parcel Service", "Logistics"),
    ("RTX", "RTX Corporation", "Aerospace / Defense"),
    ("HON", "Honeywell International", "Industrial"),
    ("LOW", "Lowe's Companies Inc.", "Retail"),
    ("SPGI", "S&P Global Inc.", "Financial Data"),
    ("GS", "Goldman Sachs Group", "Financial Services"),
    ("CAT", "Caterpillar Inc.", "Industrial / Construction"),
    ("BLK", "BlackRock Inc.", "Asset Management"),
    ("DE", "Deere & Company", "Agriculture / Industrial"),
    ("ADP", "Automatic Data Processing", "HR / Payroll"),
    ("BA", "The Boeing Company", "Aerospace"),
    ("GE", "GE Aerospace", "Aerospace / Industrial"),
    ("GM", "General Motors Company", "Automotive"),
    ("F", "Ford Motor Company", "Automotive"),
    ("IBM", "IBM Corporation", "Technology / Consulting"),
    ("MMM", "3M Company", "Industrial / Diversified"),
    ("AMGN", "Amgen Inc.", "Biotechnology"),
    ("GILD", "Gilead Sciences Inc.", "Biotechnology"),
    ("SYK", "Stryker Corporation", "Medical Devices"),
    ("MDT", "Medtronic plc", "Medical Devices"),
    ("CB", "Chubb Limited", "Insurance"),
    ("CI", "The Cigna Group", "Healthcare"),
    ("SO", "Southern Company", "Utilities"),
    ("DUK", "Duke Energy Corp.", "Utilities"),
    ("D", "Dominion Energy Inc.", "Utilities"),
    ("CL", "Colgate-Palmolive Co.", "Consumer Goods"),
    ("MO", "Altria Group Inc.", "Tobacco"),
    ("FDX", "FedEx Corporation", "Logistics"),
    ("TGT", "Target Corporation", "Retail"),
    ("SBUX", "Starbucks Corporation", "Food & Beverage"),
    ("MCD", "McDonald's Corporation", "Food & Beverage"),
    ("AXP", "American Express Co.", "Financial Services"),
    ("SCHW", "Charles Schwab Corp.", "Financial Services"),
    ("USB", "U.S. Bancorp", "Financial Services"),
    ("CHTR", "Charter Communications", "Telecom"),
    ("T", "AT&T Inc.", "Telecom"),
    ("VZ", "Verizon Communications", "Telecom"),
    ("COP", "ConocoPhillips", "Energy"),
    ("SLB", "Schlumberger Ltd.", "Energy Services"),
    ("EOG", "EOG Resources Inc.", "Energy"),
    ("PSX", "Phillips 66", "Energy / Refining"),
    ("WM", "Waste Management Inc.", "Environmental Services"),
    ("RSG", "Republic Services Inc.", "Environmental Services"),
    ("ECL", "Ecolab Inc.", "Water / Hygiene"),
    ("APD", "Air Products & Chemicals", "Industrial Gases"),
    ("SHW", "Sherwin-Williams Co.", "Chemicals / Paints"),
    ("EMR", "Emerson Electric Co.", "Industrial Automation"),
    ("ITW", "Illinois Tool Works", "Industrial"),
    ("ETN", "Eaton Corporation", "Electrical / Industrial"),
    ("DOW", "Dow Inc.", "Chemicals"),
    ("LYB", "LyondellBasell Industries", "Chemicals"),
    ("FCX", "Freeport-McMoRan Inc.", "Mining / Copper"),
    ("NEM", "Newmont Corporation", "Mining / Gold"),
    ("VALE", "Vale S.A.", "Mining / Iron Ore"),
    ("RIO", "Rio Tinto Group", "Mining"),
    ("BHP", "BHP Group Limited", "Mining"),
    ("CME", "CME Group Inc.", "Financial Exchanges"),
    ("ICE", "Intercontinental Exchange", "Financial Exchanges"),
    ("SNOW", "Snowflake Inc.", "Cloud Data"),
    ("PANW", "Palo Alto Networks", "Cybersecurity"),
    ("NOW", "ServiceNow Inc.", "Cloud Software"),
    ("SHOP", "Shopify Inc.", "E-Commerce Platform"),
    ("SQ", "Block Inc.", "Fintech"),
    ("UBER", "Uber Technologies", "Transportation"),
    ("ABNB", "Airbnb Inc.", "Travel / Hospitality"),
    ("ZM", "Zoom Video Communications", "Communications"),
    ("DDOG", "Datadog Inc.", "Cloud Monitoring"),
    ("NET", "Cloudflare Inc.", "Internet Infrastructure"),
    ("CRWD", "CrowdStrike Holdings", "Cybersecurity"),
    ("ZS", "Zscaler Inc.", "Cybersecurity"),
    ("TEAM", "Atlassian Corp.", "Developer Tools"),
    ("WDAY", "Workday Inc.", "HR / Finance Cloud"),
    ("VEEV", "Veeva Systems Inc.", "Life Sciences Cloud"),
    ("ADSK", "Autodesk Inc.", "Design Software"),
    ("INTU", "Intuit Inc.", "Financial Software"),
    ("SNPS", "Synopsys Inc.", "EDA / Semiconductors"),
    ("CDNS", "Cadence Design Systems", "EDA / Semiconductors"),
    ("AMAT", "Applied Materials Inc.", "Semiconductor Equipment"),
    ("LRCX", "Lam Research Corp.", "Semiconductor Equipment"),
    ("KLAC", "KLA Corporation", "Semiconductor Equipment"),
    ("ADI", "Analog Devices Inc.", "Semiconductors"),
    ("MRVL", "Marvell Technology", "Semiconductors"),
    ("MU", "Micron Technology", "Memory / Semiconductors"),
    ("DELL", "Dell Technologies", "Computer Hardware"),
    ("HPQ", "HP Inc.", "Computer Hardware"),
    ("WBA", "Walgreens Boots Alliance", "Pharmacy / Retail"),
    ("CVS", "CVS Health Corporation", "Healthcare / Pharmacy"),
    ("HUM", "Humana Inc.", "Health Insurance"),
    ("ELV", "Elevance Health Inc.", "Health Insurance"),
    ("LLY", "Eli Lilly and Company", "Pharmaceuticals"),
    ("NVO", "Novo Nordisk A/S", "Pharmaceuticals"),
    ("AZN", "AstraZeneca plc", "Pharmaceuticals"),
    ("BMY", "Bristol-Myers Squibb", "Pharmaceuticals"),
    ("REGN", "Regeneron Pharmaceuticals", "Biotechnology"),
    ("VRTX", "Vertex Pharmaceuticals", "Biotechnology"),
    ("ISRG", "Intuitive Surgical", "Medical Robotics"),
    ("DHR", "Danaher Corporation", "Life Sciences / Industrial"),
    ("ZTS", "Zoetis Inc.", "Animal Health"),
    ("A", "Agilent Technologies", "Life Sciences"),
    ("WAT", "Waters Corporation", "Analytical Instruments"),
    ("ROP", "Roper Technologies", "Industrial Software"),
    ("GD", "General Dynamics Corp.", "Defense"),
    ("LMT", "Lockheed Martin Corp.", "Aerospace / Defense"),
    ("NOC", "Northrop Grumman Corp.", "Aerospace / Defense"),
    ("HII", "Huntington Ingalls Ind.", "Defense / Shipbuilding"),
    ("DAL", "Delta Air Lines Inc.", "Airlines"),
    ("UAL", "United Airlines Holdings", "Airlines"),
    ("AAL", "American Airlines Group", "Airlines"),
    ("LUV", "Southwest Airlines Co.", "Airlines"),
    ("MAR", "Marriott International", "Hotels"),
    ("HLT", "Hilton Worldwide", "Hotels"),
    ("BKNG", "Booking Holdings Inc.", "Online Travel"),
    ("NFLX", "Netflix Inc.", "Streaming / Entertainment"),
    ("CMCSA", "Comcast Corporation", "Media / Telecom"),
    ("WBD", "Warner Bros. Discovery", "Entertainment"),
    ("PARA", "Paramount Global", "Entertainment"),
    ("EA", "Electronic Arts Inc.", "Gaming"),
    ("TTWO", "Take-Two Interactive", "Gaming"),
    ("RBLX", "Roblox Corporation", "Gaming / Metaverse"),
    ("U", "Unity Technologies", "Gaming / AR/VR"),
    ("SE", "Sea Limited", "E-Commerce / Gaming"),
    ("MELI", "MercadoLibre Inc.", "E-Commerce / Fintech"),
    ("JD", "JD.com Inc.", "E-Commerce"),
    ("BABA", "Alibaba Group", "E-Commerce / Cloud"),
    ("PDD", "PDD Holdings Inc.", "E-Commerce"),
    ("NIO", "NIO Inc.", "Electric Vehicles"),
    ("RIVN", "Rivian Automotive", "Electric Vehicles"),
    ("LCID", "Lucid Group Inc.", "Electric Vehicles"),
    ("TM", "Toyota Motor Corp.", "Automotive"),
    ("HMC", "Honda Motor Co.", "Automotive"),
    ("STLA", "Stellantis N.V.", "Automotive"),
    ("VW", "Volkswagen AG", "Automotive"),
    ("RACE", "Ferrari N.V.", "Luxury Automotive"),
    ("ENPH", "Enphase Energy Inc.", "Solar / Renewables"),
    ("SEDG", "SolarEdge Technologies", "Solar / Renewables"),
    ("FSLR", "First Solar Inc.", "Solar / Renewables"),
    ("BE", "Bloom Energy Corp.", "Fuel Cells"),
    ("PLUG", "Plug Power Inc.", "Green Hydrogen"),
    ("VST", "Vistra Corp.", "Power / Energy"),
    ("CEG", "Constellation Energy", "Nuclear / Clean Energy"),
    ("AEP", "American Electric Power", "Utilities"),
    ("XEL", "Xcel Energy Inc.", "Utilities / Renewables"),
    ("ES", "Eversource Energy", "Utilities"),
    ("ED", "Consolidated Edison", "Utilities"),
    ("AWK", "American Water Works", "Water Utilities"),
    ("CNP", "CenterPoint Energy", "Utilities"),
]


def search_tickers(query: str, limit: int = 8) -> list:
    """
    Search tickers by company name or ticker symbol.
    Returns list of {ticker, name, industry} dicts.
    """
    if not query or len(query) < 2:
        return []

    q = query.lower()
    results = []

    for ticker, name, industry in TICKERS:
        if q in name.lower() or q in ticker.lower():
            results.append({
                "ticker": ticker,
                "name": name,
                "industry": industry
            })
            if len(results) >= limit:
                break

    return results
